//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P81_Sister_MvcApp_1116
{
    using System;
    using System.Collections.Generic;
    
    public partial class pegawai
    {
        public string nip { get; set; }
        public string nama { get; set; }
        public string jenis_kelamin { get; set; }
        public string alamat { get; set; }
        public sbyte kodeJabatan { get; set; }
    }
}
